### ISSUE TITLE
[docs] Link to architecture is broken

### ISSUE THREAD

**Issue by kuba--** [src-d/engine-deprecated#165]
`https://github.com/src-d/engine/tree/1f47c451a1e810768d58580b604337f80f9410cb/cmd/srcd-server/README.md`

**Comment by smacker** [comment]
hi @kuba-- ! Where did you get this link? I just checked architecture link in readme and that is correct.

**Comment by kuba--** [comment]
@smacker - go to `https://docs.sourced.tech/engine/learn-more/architecture#technical-architecture`
and find a link (below) to `srcd-server`
