### ISSUE TITLE
Logging installation of bblfsh drivers

### ISSUE THREAD

**Issue by eiso** [src-d/engine-deprecated#48]
The first time I run `srcd web sql` it will install the recommended drivers for bblfsh. I'd like the log to reflect which drivers are being downloaded & installed (as we do on `srcd init` with the cli-daemon).

Current:
```
srcd web sql --port=8088
INFO[0003] this is taking a while, if this is the first time you launch this web client, it might take a few more minutes while we install all the required images 
```

Desired:
```
srcd web sql --port=8088
INFO[0003] this is taking a while, if this is the first time you launch this web client, it might take a few more minutes while we install all the required images 
INFO[0004] installing "bblfsh/python-driver:latest"
INFO[0005] installed "bblfsh/python-driver:latest"
etc...
```

**Comment by eiso** [comment]
Thinking about this, why don't we move the recommended driver installation to `srcd init`? WDYT @campoy?

**Comment by campoy** [comment]
I totally missed out on this, it's probably worth refactoring the engine a bit to get more of the logs into the console.

**Comment by carlosms** [comment]
If we switch to bblfsh `-drivers` image (#67) the driver installation step will not be needed anymore.

**Comment by campoy** [comment]
There's still need for better logging, even if all drivers are installed by default.

**Comment by smacker** [comment]
We agreed to try to get logs from server container directly.

The first step will be to get logs as is.
And then workaround some issues like concurrency, timezones, ...

there is also PR with adding context to all function that run containers: #107 extracted from prev attempt to solve this issue.
